# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentName', models.CharField(max_length=20)),
                ('Regno', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
