# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='BranchName',
            field=models.CharField(default='cse', max_length=10),
        ),
    ]
