# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 08:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApplication', '0005_auto_20180414_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='EmailId',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
