# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApplication', '0009_auto_20180421_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
