# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApplication', '0010_feesnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SemesterNo', models.CharField(choices=[('first', '1'), ('second', '2'), ('third', '3'), ('fourth', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8')], default='first', max_length=1)),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApplication.Student')),
            ],
        ),
    ]
