# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 09:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApplication', '0011_feesapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesapplication',
            name='DebitCardno',
            field=models.CharField(default='123456789111', max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AddField(
            model_name='feesapplication',
            name='cvv',
            field=models.CharField(default='123', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
