# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApplication', '0013_auto_20180421_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaidFees', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='feesapplication',
            old_name='DebitCardno',
            new_name='DebitCardNo',
        ),
        migrations.AlterField(
            model_name='feesapplication',
            name='SemesterNo',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='first', max_length=1),
        ),
        migrations.AddField(
            model_name='feespayment',
            name='ApplicationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApplication.FeesApplication'),
        ),
        migrations.AddField(
            model_name='feespayment',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApplication.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='feespayment',
            unique_together=set([('ApplicationId', 'StudentId')]),
        ),
    ]
