# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApplication', '0014_auto_20180421_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesapplication',
            name='PaidFees',
            field=models.IntegerField(default=1890),
        ),
    ]
